In [1]:
import requests
import pandas as pd
import numpy as np

In [2]:
redfin_file = 'Redfin_Scrape.csv'
trulia_file = 'Trulia_Scrape.csv'
hf_file = 'HomeFinder_Scrape.csv'

redfin_df = pd.read_csv(redfin_file)
trulia_df = pd.read_csv(trulia_file)
hf_df = pd.read_csv(hf_file)

In [3]:
redfin_df.columns, trulia_df.columns, hf_df.columns

(Index(['Unnamed: 0', 'Price', 'Address', 'City', 'Zip Code', '# of Beds',
        '# of Baths', 'sqft'],
       dtype='object'),
 Index(['Unnamed: 0', 'Price', '# of Beds', '# of Baths', 'sqft', 'Address',
        'City'],
       dtype='object'),
 Index(['Unnamed: 0', 'Price', '# of Beds', '# of Baths', 'Address', 'City',
        'Zip Code'],
       dtype='object'))

In [4]:
hf_df

,Unnamed: 0,Price,# of Beds,# of Baths,Address,City,Zip Code
0,0,$966,3 Bd,"2 bath\n | 1,423",Frank,"Dallas, TX",75210
1,1,"$317,900",3 Bd,"2 bath\n | 1,428",7947 Claremont DR,"Dallas, TX",75228
2,2,"$50,000",1 Bd,1 bath,9833 Walnut Street,"Dallas, TX",75243
3,3,"$50,000",1 Bd,1 bath,9825 Walnut Street,"Dallas, TX",75243
4,4,"$50,000",1 Bd,1 bath,9809 Walnut Street,"Dallas, TX",75243
...,...,...,...,...,...,...,...
3119,3119,"$135,900",3 Bd,2 bath,1719 Westview Terrace,"Arlington, TX",76013
3120,3120,"$365,000",3 Bd,2 bath,1405 Mount Evans Trail,"Arlington, TX",76005
3121,3121,"$265,000",4 Bd,2 bath,809 Mckenzie Place,"Arlington, TX",76018
3122,3122,"$159,000",0 Bd,0 bath,708 Houston Street,"Arlington, TX",76012
3123,3123,"$250,000",4 Bd,2 bath,5115 Eagle Nest Drive,"Arlington, TX",76017

In [5]:
trulia_df.loc[trulia_df['Address'] == '1609 Axe Dr']

,Unnamed: 0,Price,# of Beds,# of Baths,sqft,Address,City
120,120,"$185,500",3bd,2ba,"1,440 sqft",1609 Axe Dr,"Almeta,Bonita, Bella Vista, Garland, TX"

In [6]:
redfin_df

,Unnamed: 0,Price,Address,City,Zip Code,# of Beds,# of Baths,sqft
0,0,"$564,900",7200 Neches Pine Dr,"Frisco, TX",75036,3 Beds,2.5 Baths,"2,997 Sq. Ft."
1,1,"$365,000",10045 Bell Rock Rd,"Frisco, TX",75035,3 Beds,2 Baths,"2,169 Sq. Ft."
2,2,"$405,000",11017 Aurora Ln,"Frisco, TX",75035,3 Beds,2.5 Baths,"2,166 Sq. Ft."
3,3,"$449,900",9991 Slick Rock Trl,"Frisco, TX",75033,4 Beds,2.5 Baths,"2,574 Sq. Ft."
4,4,"$515,000",8326 Sitka St,"Frisco, TX",75035,4 Beds,2.5 Baths,"2,962 Sq. Ft."
5,5,"$640,000",2079 Alcove Dr,"Frisco, TX",75034,4 Beds,2.5 Baths,"2,695 Sq. Ft."
6,6,"$389,900",2910 Reynolds Ln,"Frisco, TX",75033,3 Beds,2 Baths,"2,236 Sq. Ft."
7,7,"$475,000",13714 French Creek Ln,"Frisco, TX",75035,3 Beds,2.5 Baths,"2,373 Sq. Ft."
8,8,"$930,000",4520 Florence Dr,"Frisco, TX",75034,3 Beds,3.5 Baths,"4,228 Sq. Ft."
9,9,"$439,900",7601 Blossom Ln,"Frisco, TX",75034,3 Beds,2.5 Baths,"2,383 Sq. Ft."
10,10,"$295,000",9805 Concord Dr,"Frisco, TX",75035,3 Beds,2.5 Baths,"1,396 Sq. Ft."
11,11,"$900,000",6198 Rachel Dr,"Frisco, TX",75034,4 Beds,4 Baths,"4,967 Sq. Ft."
12,12,"$339,999",12018 Chattanooga Dr,"Frisco, TX",75035,3 Beds,2 Baths,"1,417 Sq. Ft."
13,13,"$520,000",12571 Peace River Dr,"Frisco, TX",75035,5 Beds,4 Baths,"3,691 Sq. Ft."
14,14,"$460,000",9569 Lance Dr,"Frisco, TX",75035,4 Beds,2.5 Baths,"3,069 Sq. Ft."
15,15,"$325,000",7297 Chinquapin Dr,"Frisco, TX",75033,4 Beds,2 Baths,"1,995 Sq. Ft."
16,16,"$500,000",7152 Maumee Valley Ct,"Frisco, TX",75036,3 Beds,2 Baths,"2,246 Sq. Ft."
17,17,"$325,000",13160 Guerin Dr,"Frisco, TX",75035,4 Beds,2 Baths,"2,073 Sq. Ft."
18,18,"$340,000",6848 Regello Dr,"Frisco, TX",75034,2 Beds,2.5 Baths,"1,818 Sq. Ft."
19,19,"$350,000",9758 Golden Fountain Dr,"Frisco, TX",75033,4 Beds,2 Baths,"2,096 Sq. Ft."
20,20,"$325,400",11908 Clearpoint Ct,"Frisco, TX",75036,4 Beds,2 Baths,"1,852 Sq. Ft."
21,21,"$445,900",12004 Rushing Creek Dr,"Frisco, TX",75035,4 Beds,3.5 Baths,"2,860 Sq. Ft."
22,22,"$375,000",5904 Louisville Dr,"Frisco, TX",75035,4 Beds,2 Baths,"2,027 Sq. Ft."
23,23,"$675,000",1567 San Andres Dr,"Frisco, TX",75033,5 Beds,3.5 Baths,"4,668 Sq. Ft."
24,24,"$437,500",2649 Marshall Dr,"Frisco, TX",75033,4 Beds,3.5 Baths,"2,927 Sq. Ft."
25,25,"$475,000",11708 Blackhawk Dr,"Frisco, TX",75033,4 Beds,2.5 Baths,"2,860 Sq. Ft."
26,26,"$679,545",1545 Morris Ln,"Frisco, TX",75034,4 Beds,3 Baths,"3,623 Sq. Ft."
27,27,"$499,900",12923 Yale Ct,"Frisco, TX",75035,3 Beds,3 Baths,"1,882 Sq. Ft."
28,28,"$774,900",16372 Lorna Doone Ln,"Frisco, TX",75033,5 Beds,4.5 Baths,"4,147 Sq. Ft."
29,29,"$749,000",12858 Palo Duro Dr,"Frisco, TX",75033,5 Beds,5.5 Baths,"4,710 Sq. Ft."
30,30,"$369,000",2450 Thorntree Dr,"Frisco, TX",75033,4 Beds,3 Baths,"2,207 Sq. Ft."
31,31,"$425,000",7927 Canal St,"Frisco, TX",75034,2 Beds,2.5 Baths,"1,706 Sq. Ft."
32,32,"$1,150,000",15246 Crystal Beach Ln,"Frisco, TX",75035,6 Beds,5 Baths,"4,813 Sq. Ft."
33,33,"$1,152,990",2481 Haft River Rd,"Frisco, TX",75034,5 Beds,4 Baths,"4,002 Sq. Ft."
34,34,"$540,000",8260 Fairview Dr,"Frisco, TX",75033,3 Beds,3.5 Baths,"2,128 Sq. Ft."
35,35,"$1,200,000",6006 Connely Dr,"Frisco, TX",75034,5 Beds,4.5 Baths,"5,253 Sq. Ft."
36,36,"$925,000",5111 Stillwater Trl,"Frisco, TX",75034,4 Beds,4.5 Baths,"4,061 Sq. Ft."
37,37,"$625,000",1403 Crockett Dr,"Frisco, TX",75033,4 Beds,3.5 Baths,"3,757 Sq. Ft."
38,38,"$329,000",12144 Cardinal Creek Dr,"Frisco, TX",75033,3 Beds,2 Baths,"1,805 Sq. Ft."
39,39,"$430,000",949 Imperial Valley Ln,"Frisco, TX",75036,2 Beds,2 Baths,"1,786 Sq. Ft."
40,40,"$350,000",2260 Lariat Trl,"Frisco, TX",75036,3 Beds,2 Baths,"1,841 Sq. Ft."

In [ ]:
for i in hf_df.index:
    hf_df['City'][i] = hf_df['City'][i][:-4]
    hf_df['# of Beds'][i] = hf_df['# of Beds'][i][:hf_df['# of Beds'][i].find(' ')]
    hf_df['# of Baths'][i] = hf_df['# of Baths'][i][:hf_df['# of Baths'][i].find(' ')]
    hf_df['Price'][i] = hf_df['Price'][i].replace('$', '')
    hf_df['Price'][i] = hf_df['Price'][i].replace(',', '')
    
hf_df['# of Beds'] = hf_df['# of Beds'].astype(float)
hf_df['# of Baths'] = hf_df['# of Baths'].astype(float)
hf_df['Price'] = hf_df['Price'].astype(int)

hf_df

<ipython-input-7-7e48ed86f303>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hf_df['City'][i] = hf_df['City'][i][:-4]
<ipython-input-7-7e48ed86f303>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hf_df['# of Beds'][i] = hf_df['# of Beds'][i][:hf_df['# of Beds'][i].find(' ')]
<ipython-input-7-7e48ed86f303>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hf_df['# of Baths'][i] = hf_df['# of Baths'][i][:hf_df['# of Baths'][i].find(' ')]
<ipython-input-7-7e48ed86f303>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hf_df['Price'][i] = hf_df['Price'][i].replace('$', '')
<ipython-input-7-7e48ed86f303>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hf_df['Price'][i] = hf_df['Price'][i].replace(',', '')

In [ ]:
for i in trulia_df.index:
    trulia_df['City'][i] = trulia_df['City'][i][trulia_df['City'][i].find(', ') + 2 : -4]
    trulia_df['City'][i] = trulia_df['City'][i][trulia_df['City'][i].find(', ') + 1 :]
    trulia_df['City'][i] = trulia_df['City'][i].lstrip()
    trulia_df['# of Beds'][i] = trulia_df['# of Beds'][i][:trulia_df['# of Beds'][i].find('b')]
    trulia_df['# of Baths'][i] = trulia_df['# of Baths'][i][:trulia_df['# of Baths'][i].find('b')]
    trulia_df['Price'][i] = trulia_df['Price'][i].replace('$', '')
    trulia_df['Price'][i] = trulia_df['Price'][i].replace(',', '')
    trulia_df['sqft'][i] = trulia_df['sqft'][i][:trulia_df['sqft'][i].find(' ')]
    trulia_df['sqft'][i] = trulia_df['sqft'][i].replace(',', '')
    
trulia_df['# of Beds'] = trulia_df['# of Beds'].astype(float)
trulia_df['# of Baths'] = trulia_df['# of Baths'].astype(float)
trulia_df['Price'] = trulia_df['Price'].astype(int)
trulia_df['sqft'] = trulia_df['sqft'].astype(int)

trulia_df

In [ ]:
for i in redfin_df.index:
    redfin_df['City'][i] = redfin_df['City'][i][: -4]
    redfin_df['# of Beds'][i] = redfin_df['# of Beds'][i][:redfin_df['# of Beds'][i].find(' ')]
    redfin_df['# of Baths'][i] = redfin_df['# of Baths'][i][:redfin_df['# of Baths'][i].find(' ')]
    redfin_df['Price'][i] = redfin_df['Price'][i].replace('$', '')
    redfin_df['Price'][i] = redfin_df['Price'][i].replace(',', '')
    redfin_df['sqft'][i] = redfin_df['sqft'][i][:redfin_df['sqft'][i].find(' ')]
    redfin_df['sqft'][i] = redfin_df['sqft'][i].replace(',', '')
    
redfin_df['# of Beds'] = redfin_df['# of Beds'].astype(float)
redfin_df['# of Baths'] = redfin_df['# of Baths'].astype(float)
redfin_df['Price'] = redfin_df['Price'].astype(int)
redfin_df['sqft'] = redfin_df['sqft'].astype(int)

redfin_df

In [ ]:
hf_df = hf_df.loc[hf_df['Price'] >= 10000]
hf_df = hf_df.loc[hf_df['# of Beds'] != 0]
hf_df = hf_df.loc[hf_df['# of Baths'] != 0]

hf_df

In [ ]:
hf_sq = [None] * 2954
tru_zip = [None] * 240

hf_df['sqft'] = hf_sq
trulia_df['Zip Code'] = tru_zip

trulia_df

In [ ]:
hf_df = hf_df[['Address', 'City', 'Zip Code', 'Price', 'sqft', '# of Beds', '# of Baths']]
trulia_df = trulia_df[['Address', 'City', 'Zip Code', 'Price', 'sqft', '# of Beds', '# of Baths']]
redfin_df = redfin_df[['Address', 'City', 'Zip Code', 'Price', 'sqft', '# of Beds', '# of Baths']]

redfin_df.columns, trulia_df.columns, hf_df.columns

In [ ]:
dfs = [hf_df, trulia_df, redfin_df]
all_dfs = pd.concat([df.squeeze() for df in dfs], ignore_index=True)

all_dfs

In [ ]:
all_dfs = all_dfs.drop(all_dfs.loc[all_dfs['Address'].duplicated() == True].index)

In [ ]:
all_dfs = all_dfs[all_dfs['Address'].notna()]

In [ ]:
all_dfs.to_csv("Final_DataFrame.csv")